/**
 * translate-full.ts
 * Comprehensive translation of English text in Spanish skeleton HTML files.
 * Extracts all text content outside <pre><code> blocks, translates paragraph by paragraph
 * using a local LLM, and reconstructs the HTML.
 *
 * Usage: bun scripts/translate-full.ts
 */

import * as fs from "fs";
import * as path from "path";
import { ES_FILES as FILES } from "./translate-lib";

const BASE = "./docs";

// Extended dictionary - comprehensive phrase replacements
const EXTENDED_DICT: [string, string][] = [
  // Meta description fix
  ["Introduction to Claude Code and Multi-Agent Harness", "Introducción a Claude Code y Multi-Agent Harness"],

  // ch03 specific
  ["To use multi-agent systems like co-consult and co-deck, you need a few additional tools.", "Para usar sistemas multi-agente como co-consult y co-deck, necesitas algunas herramientas adicionales."],
  ["this chapter walks you through installing everything at once and verifying it works.", "este capítulo te guía a través de la instalación de todo a la vez y la verificación de que funcione."],
  ["Pre-flight checklist (subscriptions, accounts, system requirements)", "Lista de verificación previa al vuelo (suscripciones, cuentas, requisitos del sistema)"],
  ["Preparing the", "Preparando la"],
  ["folder", "carpeta"],
  ["OS-specific installation (MacOS, Windows, Linux)", "Instalación específica por sistema operativo (MacOS, Windows, Linux)"],
  ["Verification and troubleshooting", "Verificación y solución de problemas"],
  ["Before you begin installing anything, make sure the following items are ready.", "Antes de comenzar a instalar cualquier cosa, asegúrate de que los siguientes elementos estén listos."],
  ["All of them are", "Todos ellos son"],
  ["required", "requeridos"],
  ["to use the", "para usar el"],
  ["is built on Claude Code, and using Claude Code requires a", "está construido sobre Claude Code, y usar Claude Code requiere una"],
  ["Paid subscription for Claude Desktop App and Claude Code", "Suscripción de pago para Claude Desktop App y Claude Code"],
  ["Check at", "Verifica en"],
  ["Required for accessing open-source repositories and using GitHub CLI", "Requerido para acceder a repositorios de código abierto y usar GitHub CLI"],
  ["Sign up at", "Regístrate en"],
  ["free", "gratis"],
  ["Required for Claude Desktop App login and Claude Code authentication", "Requerido para el inicio de sesión de Claude Desktop App y la autenticación de Claude Code"],
  ["A free Claude account", "Una cuenta gratuita de Claude"],
  ["will not work", "no funcionará"],
  ["with Claude Desktop App.", "con Claude Desktop App."],
  ["You need a Pro subscription.", "Necesitas una suscripción Pro."],
  ["If you haven't subscribed yet, sign up for", "Si aún no te has suscrito, regístrate en"],
  ["at claude.ai/subscribe.", "en claude.ai/subscribe."],
  ["Required Subscriptions", "Suscripciones requeridas"],
  ["Item", "Elemento"],
  ["How to Check", "Cómo verificar"],
  ["To run the", "Para ejecutar el"],
  ["your computer must meet the following minimum specifications.", "tu computadora debe cumplir con las siguientes especificaciones mínimas."],
  ["is the minimum memory needed to run Claude Desktop App alongside additional tools (Git, Bun, etc.).", "es la memoria mínima necesaria para ejecutar Claude Desktop App junto con herramientas adicionales (Git, Bun, etc.)."],
  ["If you plan to run multiple agents simultaneously or keep a browser open,", "Si planeas ejecutar múltiples agentes simultáneamente o mantener un navegador abierto,"],
  ["or more is recommended.", "o más es recomendado."],
  ["provides room for tool installations and project files.", "proporciona espacio para instalaciones de herramientas y archivos de proyecto."],
  ["If you plan to work on multiple projects, you may need more space over time.", "Si planeas trabajar en múltiples proyectos, es posible que necesites más espacio con el tiempo."],
  ["If you are using a remote access environment (e.g., cloud desktop, SSH server), see", "Si usas un entorno de acceso remoto (por ejemplo, escritorio en la nube, servidor SSH), consulta"],
  ["We will create a", "Crearemos una"],
  ["dedicated", "dedicada"],
  ["to store the scripts and configuration files used during installation.", "para almacenar los scripts y archivos de configuración utilizados durante la instalación."],
  ["This folder will serve as the home base for all future hands-on exercises.", "Esta carpeta servirá como la base principal para todos los ejercicios prácticos futuros."],
  ["Creating the Folder", "Creando la carpeta"],
  ["Run the command below for your operating system.", "Ejecuta el siguiente comando para tu sistema operativo."],
  ["The", "La"],
  ["folder should be created under the directory where you store your Git projects.", "carpeta debe crearse en el directorio donde almacenas tus proyectos de Git."],
  ["This folder will store installation verification scripts, configuration files, and project templates going forward.", "Esta carpeta almacenará scripts de verificación de instalación, archivos de configuración y plantillas de proyecto en adelante."],
  ["You can change the folder location at any time, but", "Puedes cambiar la ubicación de la carpeta en cualquier momento, pero"],
  ["uses the paths above as the reference standard.", "usa las rutas anteriores como estándar de referencia."],
  ["The setup folder will have the following structure.", "La carpeta de configuración tendrá la siguiente estructura."],
  ["Right now it is empty, but each item will be populated as you progress through the installation.", "Ahora mismo está vacía, pero cada elemento se irá llenando a medida que avances en la instalación."],
  ["Avoid spaces or non-English characters in folder paths.", "Evita espacios o caracteres no ingleses en las rutas de las carpetas."],
  ["Paths like", "Rutas como"],
  ["can cause errors with some tools.", "pueden causar errores con algunas herramientas."],
  ["Stick to English-only paths like", "Usa solo rutas en inglés como"],
  ["to stay safe.", "para estar seguro."],
  ["makes it easy to install all the required tools.", "facilita la instalación de todas las herramientas requeridas."],
  ["is the most widely used open-source package manager for MacOS.", "es el gestor de paquetes de código abierto más utilizado para MacOS."],
  ["Check if Homebrew is installed", "Verifica si Homebrew está instalado"],
  ["Open", "Abre"],
  ["and run the following command.", "y ejecuta el siguiente comando."],
  ["If a version number appears, Homebrew is already installed", "Si aparece un número de versión, Homebrew ya está instalado"],
  ["skip to the next step.", "salta al siguiente paso."],
  ["If you see", "Si ves"],
  ["you need to install Homebrew first.", "necesitas instalar Homebrew primero."],
  ["only if needed", "solo si es necesario"],
  ["Run the official installation script from Homebrew's website.", "Ejecuta el script de instalación oficial del sitio web de Homebrew."],
  ["Copy and paste this command into your terminal.", "Copia y pega este comando en tu terminal."],
  ["Once installation completes, close and reopen the terminal.", "Una vez que la instalación se complete, cierra y vuelve a abrir la terminal."],
  ["Install Git", "Instalar Git"],
  ["is a version control system.", "es un sistema de control de versiones."],
  ["It tracks changes to your code and integrates with GitHub for project management.", "Rastrea los cambios en tu código y se integra con GitHub para la gestión de proyectos."],
  ["is a foundational tool for Claude Code and the multi-agent system.", "es una herramienta fundamental para Claude Code y el sistema multi-agente."],
  ["Install GitHub CLI", "Instalar GitHub CLI"],
  ["lets you use GitHub directly from the terminal.", "te permite usar GitHub directamente desde la terminal."],
  ["uses it to create and manage GitHub repositories.", "lo usa para crear y gestionar repositorios de GitHub."],
  ["Install Bun", "Instalar Bun"],
  ["is a JavaScript/TypeScript runtime.", "es un runtime de JavaScript/TypeScript."],
  ["It serves as an alternative to Node.js and is required to run the", "Sirve como alternativa a Node.js y es necesario para ejecutar los"],
  ["automation scripts and configuration validation tools.", "scripts de automatización y herramientas de validación de configuración."],
  ["It is known for being fast and easy to install.", "Es conocido por ser rápido y fácil de instalar."],
  ["Authenticate GitHub CLI", "Autenticar GitHub CLI"],
  ["Link your GitHub account to", "Vincula tu cuenta de GitHub a"],
  ["This step is required before Claude Code can use GitHub features.", "Este paso es necesario antes de que Claude Code pueda usar las funciones de GitHub."],
  ["Follow the prompts to select", "Sigue las instrucciones para seleccionar"],
  ["When your browser opens, log in with your GitHub account to complete authentication.", "Cuando se abra tu navegador, inicia sesión con tu cuenta de GitHub para completar la autenticación."],
  ["is assumed to be already installed from", "se asume que ya está instalado desde"],
  ["If you have not installed it yet, complete", "Si aún no lo has instalado, completa"],
  ["first.", "primero."],
  ["On Windows, each tool is installed individually.", "En Windows, cada herramienta se instala individualmente."],
  ["Use", "Usa"],
  ["or", "o"],
  ["to proceed.", "para continuar."],
  ["On Windows, you may need to run PowerShell as an administrator.", "En Windows, es posible que necesites ejecutar PowerShell como administrador."],
  ["Right-click PowerShell in the Start Menu and select", "Haz clic derecho en PowerShell en el Menú Inicio y selecciona"],
  ["Run as Administrator", "Ejecutar como administrador"],
  ["is a version control system, essential for Claude Code and GitHub integration.", "es un sistema de control de versiones, esencial para Claude Code y la integración con GitHub."],
  ["This tool lets you use GitHub from the terminal.", "Esta herramienta te permite usar GitHub desde la terminal."],
  ["Run the following command in PowerShell to install Bun.", "Ejecuta el siguiente comando en PowerShell para instalar Bun."],
  ["After installation, you must", "Después de la instalación, debes"],
  ["restart PowerShell", "reiniciar PowerShell"],
  ["for the", "para que el"],
  ["command to be recognized.", "comando sea reconocido."],
  ["Download the installer from", "Descarga el instalador desde"],
  ["and run it.", "y ejecútalo."],
  ["Default installation options are fine.", "Las opciones de instalación predeterminadas son adecuadas."],
  ["Download the Windows installer from", "Descarga el instalador de Windows desde"],
  ["On Linux (Ubuntu/Debian-based), use the", "En Linux (basado en Ubuntu/Debian), usa el"],
  ["package manager and official installation scripts.", "gestor de paquetes y los scripts de instalación oficiales."],
  ["For other Linux distributions (Fedora, Arch, etc.), adjust the package manager commands accordingly.", "Para otras distribuciones de Linux (Fedora, Arch, etc.), ajusta los comandos del gestor de paquetes correspondientemente."],
  ["For example, use", "Por ejemplo, usa"],
  ["on Fedora or", "en Fedora o"],
  ["on Arch.", "en Arch."],
  ["Update system packages", "Actualizar paquetes del sistema"],
  ["Before installing anything, update your system packages to the latest versions.", "Antes de instalar cualquier cosa, actualiza los paquetes de tu sistema a las últimas versiones."],
  ["is pre-installed on most Ubuntu/Debian systems, but verify and install if needed.", "viene preinstalado en la mayoría de los sistemas Ubuntu/Debian, pero verifica e instala si es necesario."],
  ["Add the official GitHub repository and install", "Añade el repositorio oficial de GitHub e instala"],
  ["Use the official installation script to install Bun.", "Usa el script de instalación oficial para instalar Bun."],
  ["After installation completes, restart the terminal or apply the PATH update with:", "Después de que la instalación se complete, reinicia la terminal o aplica la actualización del PATH con:"],
  ["Now let's confirm that all tools were installed correctly.", "Ahora confirmemos que todas las herramientas se instalaron correctamente."],
  ["Open a terminal and run the following commands in order.", "Abre una terminal y ejecuta los siguientes comandos en orden."],
  ["Version Check", "Verificación de versión"],
  ["Verify that each tool displays a version number.", "Verifica que cada herramienta muestre un número de versión."],
  ["If a version number appears, the installation was successful.", "Si aparece un número de versión, la instalación fue exitosa."],
  ["Expected result:", "Resultado esperado:"],
  ["(version number may vary)", "(el número de versión puede variar)"],
  ["Run the Verification Script", "Ejecutar el script de verificación"],
  ["The verification script in the setup folder checks the installation status of all tools at once.", "El script de verificación en la carpeta de configuración verifica el estado de instalación de todas las herramientas a la vez."],
  ["The verification script checks whether Git, GitHub CLI, and Bun are installed, displays their versions, and verifies your GitHub authentication status.", "El script de verificación comprueba si Git, GitHub CLI y Bun están instalados, muestra sus versiones y verifica el estado de tu autenticación de GitHub."],
  ["Sample Verification Results", "Resultados de verificación de ejemplo"],
  ["When all tools are properly installed, you will see output like this:", "Cuando todas las herramientas estén correctamente instaladas, verás un resultado como este:"],
  ["Verification Checklist", "Lista de verificación"],
  ["Does", "¿"],
  ["display a version number?", "muestra un número de versión?"],
  ["show your logged-in account?", "muestra tu cuenta iniciada?"],
  ["If all items are checked, your installation is complete!", "¡Si todos los elementos están marcados, tu instalación está completa!"],
  ["Here are the most common installation problems and their solutions.", "Aquí están los problemas de instalación más comunes y sus soluciones."],
  ["If something goes wrong, look for your issue in the list below.", "Si algo sale mal, busca tu problema en la lista a continuación."],
  ["Installation Failed:", "Falló la instalación:"],
  ["was installed but may not have been added to the system PATH.", "se instaló pero puede que no se haya añadido al PATH del sistema."],
  ["Cause:", "Causa:"],
  ["Solution:", "Solución:"],
  ["Close the terminal completely and reopen it.", "Cierra la terminal completamente y vuelve a abrirla."],
  ["is still not recognized, manually add the Bun installation path to PATH.", "aún no se reconoce, añade manualmente la ruta de instalación de Bun al PATH."],
  ["To apply this permanently, add", "Para aplicar esto permanentemente, añade"],
  ["to the PATH variable in the System Environment Variables editor.", "a la variable PATH en el editor de variables de entorno del sistema."],
  ["Authentication Error:", "Error de autenticación:"],
  ["The GitHub CLI browser authentication did not complete, or the authentication token has expired.", "La autenticación del navegador de GitHub CLI no se completó, o el token de autenticación ha expirado."],
  ["Re-run the authentication process from the beginning.", "Vuelve a ejecutar el proceso de autenticación desde el principio."],
  ["select the following options:", "selecciona las siguientes opciones:"],
  ["What account?", "¿Qué cuenta?"],
  ["Preferred protocol?", "¿Protocolo preferido?"],
  ["Authenticate Git?", "¿Autenticar Git?"],
  ["If the browser does not open automatically, copy the", "Si el navegador no se abre automáticamente, copia el"],
  ["one-time code", "código de un solo uso"],
  ["shown in the terminal and enter it manually at", "que se muestra en la terminal e introdúcelo manualmente en"],
  ["Connection Error", "Error de conexión"],
  ["Internet connectivity issues, Anthropic server outage, or an expired authentication token.", "Problemas de conectividad a Internet, interrupción del servidor de Anthropic o un token de autenticación expirado."],
  ["Verify that your internet connection is working.", "Verifica que tu conexión a Internet funcione."],
  ["Try visiting another website", "Intenta visitar otro sitio web"],
  ["in your browser.", "en tu navegador."],
  ["Sign out of Claude Desktop App and sign back in.", "Cierra sesión en Claude Desktop App y vuelve a iniciar sesión."],
  ["From the menu, select", "Desde el menú, selecciona"],
  ["then log in again with your Anthropic account.", "luego inicia sesión de nuevo con tu cuenta de Anthropic."],
  ["Quit Claude Desktop App completely and relaunch it.", "Cierra Claude Desktop App completamente y vuelve a lanzarlo."],
  ["press", "presiona"],
  ["right-click the system tray icon and select", "haz clic derecho en el icono de la bandeja del sistema y selecciona"],
  ["If the problem persists, check Anthropic's status page at", "Si el problema persiste, verifica la página de estado de Anthropic en"],
  ["to see if there is a known service disruption.", "para ver si hay una interrupción del servicio conocida."],
  ["Command Not Recognized", "Comando no reconocido"],
  ["was installed but its path was not added to the system PATH.", "se instaló pero su ruta no se añadió al PATH del sistema."],
  ["Check that the Git installation path (usually", "Verifica que la ruta de instalación de Git (generalmente"],
  [") is included in the system", ") esté incluida en la"],
  ["environment variable.", "variable de entorno del sistema."],
  ["Search for", "Busca"],
  ["in the Windows search bar and open", "en la barra de búsqueda de Windows y abre"],
  ["Restart the terminal.", "Reinicia la terminal."],
  ["If the problem persists, verify the PATH with:", "Si el problema persiste, verifica el PATH con:"],
  ["Check whether the Git installation path (usually", "Verifica si la ruta de instalación de Git (generalmente"],
  [") is included.", ") está incluida."],
  ["Other Issues", "Otros problemas"],
  ["command errors", "errores del comando"],
  ["installation is corrupted", "instalación está corrupta"],
  ["Run", "Ejecuta"],
  ["and follow the instructions", "y sigue las instrucciones"],
  ["command not found", "comando no encontrado"],
  ["not installed", "no instalado"],
  ["Install", "Instala"],
  ["from Microsoft Store", "desde Microsoft Store"],
  ["Script execution errors", "Errores de ejecución de scripts"],
  ["version is outdated", "versión está desactualizada"],
  ["Network timeout", "Tiempo de espera de red agotado"],
  ["Firewall or proxy blocking", "Firewall o proxy bloqueando"],
  ["Contact your network administrator to check proxy settings", "Contacta a tu administrador de red para verificar la configuración del proxy"],
  ["If you need a remote access environment (SSH, cloud desktop, WSL, etc.), see", "Si necesitas un entorno de acceso remoto (SSH, escritorio en la nube, WSL, etc.), consulta"],
  ["Installation instructions for WSL (Windows Subsystem for Linux) are also included in that appendix.", "Las instrucciones de instalación para WSL (Subsistema de Windows para Linux) también se incluyen en ese apéndice."],
  ["Windows-Specific Tips", "Consejos específicos de Windows"],
  ["and Bun run more reliably in PowerShell.", "y Bun funcionan de manera más confiable en PowerShell."],
  ["We recommend setting PowerShell as your default terminal.", "Recomendamos establecer PowerShell como tu terminal predeterminada."],
  ["If a command is not recognized after installation, restart the terminal.", "Si un comando no se reconoce después de la instalación, reinicia la terminal."],
  ["If the problem persists, verify that the installation path was added to the system", "Si el problema persiste, verifica que la ruta de instalación se haya añadido al"],
  ["environment variable.", "variable de entorno del sistema."],
  ["Installing Git for Windows also installs", "Instalar Git para Windows también instala"],
  ["a terminal that provides a Linux/Mac-like command environment.", "una terminal que proporciona un entorno de comandos similar a Linux/Mac."],
  ["If you are comfortable with it, feel free to use Git Bash instead.", "Si te sientes cómodo con él, siéntete libre de usar Git Bash en su lugar."],
  ["Option 1: Install with winget", "Opción 1: Instalar con winget"],
  ["Option 2: Download directly", "Opción 2: Descargar directamente"],
  ["Windows 10+", "Windows 10+"],
  // Common table cell content
  ["GB or more", "GB o más"],
  ["Stable broadband", "Banda ancha estable"],
  ["Latest version recommended", "Se recomienda la última versión"],
  ["Beginners, casual use", "Principiantes, uso casual"],
  ["Serious learners, professionals", "Estudiantes serios, profesionales"],
  ["Heavy daily users, teams", "Usuarios intensivos diarios, equipos"],
  ["Good, not expert", "Bueno, no experto"],
];

function translateFileContent(html: string): string {
  let result = html;

  // Apply extended dictionary (longest phrases first - already ordered)
  for (const [english, spanish] of EXTENDED_DICT) {
    // Only replace in text content, not inside tags
    // Use a simple replaceAll since we already split by code blocks isn't needed here
    result = result.split(english).join(spanish);
  }

  return result;
}

function processFile(relPath: string) {
  const filePath = path.join(BASE, relPath);
  let html = fs.readFileSync(filePath, "utf-8");
  html = translateFileContent(html);
  fs.writeFileSync(filePath, html, "utf-8");
  console.log(`✓ Translated: ${relPath}`);
}

// Main
for (const file of FILES) {
  processFile(file);
}
console.log(`\nDone! ${FILES.length} files content-translated.`);
